# Data Simulation

This notebook try to randomly generate the data for algorithm training purpose. It doesn't have to be very consistent nor logical, they provide a data structure / format for us to carry on the training

In [1]:
import pandas as pd
import numpy as np
from faker import Faker
from data.fake_data import *
from datetime import date

In [2]:
sample_size = 120

random_state = 42

fake = Faker(['zh_CN', 'en_US', 'ja_JP', 'en_IN', 'de_DE', 'en_GB'])

Faker.seed(random_state)
np.random.seed(random_state)

# # # # # # # # # # # # #
# simulation portion
# # # # # # # # # # # # #

names = [fake.name() for _ in range(sample_size)]
sim_subject = np.random.choice(subjects, sample_size)
sim_school = [np.random.choice(schools, np.random.randint(1, 3)) for _ in range(sample_size)]
sim_gradyr = [np.random.choice(list(range(2010, 2021)), len(sim_school[i]), replace=False) for i in range(sample_size)]
sim_zip = np.random.choice(zips, sample_size)
sim_industries = np.random.choice(industries, sample_size)
sim_titles = np.random.choice(titles, sample_size)
sim_countries = np.random.choice(countries, sample_size)
sim_languages = [np.random.choice(languages, np.random.randint(1, 4), replace=False) for _ in range(sample_size)]

################
# Add on 22 Apr, to better fit the latest product goal, include two more columns for simulation
################

# to simulate the situation that some ppl are connected already, avoid seeing them again
sim_connected = [np.random.choice(range(0, sample_size), i) for i in np.random.choice(range(20), sample_size)]

# priority tags, to simulate the situation that people select the tags explicitly
sim_tags = [['tag_' + str(i) for i in np.random.choice(range(0, 20), i)] for i in np.random.choice(range(4), sample_size)]

In [3]:
sim_data = pd.DataFrame(np.vstack([
    names, 
    sim_school,
    sim_subject, 
    sim_gradyr, 
    sim_zip, 
    sim_industries, 
    sim_titles,
    sim_countries,
    sim_languages,
    sim_connected,
    sim_tags
])).T

sim_data.columns = ['name', 'school', 'subject', 'grad_yr', 'zip', 'industry', 'title', 'country', 'language', 'connected', 'priority_tags']

sim_data.reset_index()

,index,name,school,subject,grad_yr,zip,industry,title,country,language,connected,priority_tags
0,0,青山 さゆり,[South China Normal University],Biology,[2020],94102,Banking,Student,France,"[Spanish, Korean]","[112, 119, 20, 98, 31, 93]","[tag_1, tag_12]"
1,1,傅红梅,[University of California Berkeley],Mechanical Engineering,[2014],94103,Banking,UX Designer,United States,"[Spanish, Cantonese]","[118, 38, 112, 11]","[tag_18, tag_5, tag_15]"
2,2,李红霞,"[University of Chicago, University of Chicago]",Graphic Design,"[2018, 2014]",94108,Management Consulting,UX Designer,China,[Spanish],[],[]
3,3,Daniel Wagner,[University of Hong Kong],Law,[2012],94104,Computer Software,Product Manager,United States,"[Chinese, Korean, Cantonese]","[104, 46, 17, 20, 12, 20, 7, 45, 103, 109, 6, 22]","[tag_1, tag_7]"
4,4,Cristian Santos,[University of Michigan Ann Arbor],Business Administration and Management,[2020],94101,Financial Services,Product Manager,China,"[Korean, Japanese]","[107, 95, 74, 85, 21, 106, 88, 21, 91, 28, 12,...",[tag_16]
...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,Timothy Ryan,[University of California Los Angeles],Statistics,[2013],94108,Higher Education,UX Designer,United States,"[Korean, Cantonese]","[45, 107, 20, 43, 10, 102, 67, 114, 0, 91, 62,...",[tag_0]
116,116,钟慧,"[University of Chicago, University of Michigan...",Advertising,"[2018, 2010]",94105,Computer Software,Researcher,UK,"[Spanish, Chinese, Korean]","[16, 98, 81, 103, 85, 23, 18, 36, 102, 84, 7, ...","[tag_19, tag_15, tag_14]"
117,117,Jessica Adams,[University of Michigan Ann Arbor],Accounting,[2010],94110,Computer Software,Data Scientist,Japan,"[Japanese, Korean]","[90, 116, 97, 10, 53, 44, 46, 11, 117, 20, 117]",[]
118,118,Dr. Sebastiano Roskoth,[Stanford University],Advertising,[2012],94103,Computer Software,Product Manager,United States,"[Korean, Chinese]","[10, 102, 91, 4, 80, 55, 19, 40, 45, 11, 69, 1...",[]
119,119,Jamie Miles-Ahmed,[The Chinese University of Hong Kong],Biochemistry,[2015],94108,Accounting,Data Scientist,China,"[Chinese, Korean]","[51, 95, 69, 54, 99, 101, 74, 32, 61, 87, 22, ...","[tag_16, tag_7, tag_11]"

In [4]:
file_name = 'data/sim_data_' + str(sim_data.shape[0]) + '_' + date.today().strftime("%d%b%Y") + '.csv'

sim_data.to_csv(file_name, index=False)